# Generated by Django 4.1.3 on 2023-02-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appodb',
            name='Date',
            field=models.IntegerField(),
        ),
    ]
