# Generated by Django 4.1.3 on 2023-02-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_appodb_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appodb',
            name='Date',
            field=models.DateField(),
        ),
    ]
