# Generated by Django 4.1.7 on 2023-02-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_appodb_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appodb',
            name='Date',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
    ]
