# Generated by Django 4.1.7 on 2023-02-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_appodb_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appodb',
            name='Email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
